Site/urls.py
from django.urls import path, include
from django.contrib import admin
from .views import index

from drf_yasg.views import get_schema_view
from drf_yasg.openapi import Info, Contact, License
from rest_framework.permissions import AllowAny


schema_view = get_schema_view(
   Info(
      title="Snippets API",
      default_version='v1',
      description="Test description",
      terms_of_soft="https://www.google.com/policies/terms/",
      contact=Contact(email="contact@snippets.local"),
      license=License(name="BSD License"),
   ),
   public=True,
   permission_classes=[AllowAny]
)


urlpatterns = [
    path('api/soft_loading_api/v1/', include('SoftLoading.api_v1.urls')),
    path('api/profiles_api/v1/',     include('Profiles.api_v1.urls')),
    path('django_templates/',    include('SoftLoading.urls', namespace='soft_loading')),
    path('admin/',               admin.site.urls),
    path('', index),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui')
]

SoftLoading/api_v1/urls.py
from django.urls import path, include
from .views import *
from rest_framework.routers import DefaultRouter


# All abilities encapsulated:
router = DefaultRouter()
router.register('softs',    SoftViewSet)
router.register('payments', PaymentViewSet)
router.register('files', FileViewSet)


urlpatterns = [
    path('', include(router.urls)),
    path('manage_payment_status/',                PaymentStatusUserView.as_view()),
    path('manage_payment_status_admin/<int:pk>/', PaymentStatusAdminView.as_view()),
    path('manage_payment_soft/',                  PaymentSoftView.as_view()),
    path('asinc_pay_service/',           AsincServiceMount.as_view())
]

SoftLoading/urls.py
from django.urls import path
from .views import *


app_name = 'SoftLoading'
urlpatterns = [
    path('catalog/', catalog,   name='catalog'),
    path('soft/<int:soft_id>/', soft, name='soft'),
]

SoftLoading/api_v1/views.py
from django.utils.decorators import method_decorator
from minio import S3Error
from rest_framework.viewsets import ModelViewSet
from rest_framework.views import APIView
from rest_framework.request import Request
from rest_framework.response import Response
from django.http import FileResponse

from SoftLoading.models import Soft, File, Payment
from django.db.models import Q, Sum
from rest_framework.permissions import IsAuthenticatedOrReadOnly
from .permissions import IsManager, IsAdmin, IsUser

from .serializers import SoftSerializer, FilesSerialiser, PaymentSerializer
from rest_framework.exceptions import ValidationError, PermissionDenied, NotFound
from SoftLoading.validators import SOFT_STATUSES, PAYMENT_STATUSES
from datetime import datetime

from Site.settings import MINIO, AWS_STORAGE_BUCKET_NAME, WEB_SERVICE_SEKRET_KEY
from pathlib import Path
from django.views.decorators.csrf import csrf_exempt


def add_count_option(instance, request: Request):
    if request.GET.get('count') == 'true':
        queryset = instance.get_queryset()
        return Response({'count': queryset.count()})


def get_model_obj(model, pk, force_empty=False):
    obj = model.objects.filter(id=pk).first()
    if not obj and not force_empty:
        raise NotFound({'detail': 'object not found'})
    return obj


def get_draft(request):
    return Payment.objects.filter(user=request.user.id,
                                  status=PAYMENT_STATUSES[0]).first()


class SoftViewSet(ModelViewSet):
    serializer_class = SoftSerializer
    queryset = Soft.objects.none()

    http_method_names = ['get', 'post', 'delete', 'put']

    def get_permissions(self):
        match self.action:
            case 'list' | 'retrieve':
                permission_classes = [IsAuthenticatedOrReadOnly]
            case _:
                permission_classes = [IsManager | IsAdmin]
        return [permission() for permission in permission_classes]

    def get_queryset(self):
        soft = Soft.objects.filter(status=SOFT_STATUSES[0])

        # Processing search:
        search = self.request.GET.get('search')
        if search:
            soft = soft.filter(
                Q(name__icontains=search) | Q(description__icontains=search) |
                (Q(price=search) if search.isnumeric() else Q(pk__in=[])) |
                Q(file__platform__icontains=search)
            ).distinct()  # Last query can put few same result

        # Processing price filter:
        match self.request.GET.get('cheap'):
            case 'up':
                soft = soft.order_by('price')
            case 'down':
                soft = soft.order_by('-price')

        # Processing price range filter:
        cheap_start = self.request.GET.get('cheap_start')
        if cheap_start:
            soft = soft.filter(price__gte=cheap_start)

        cheap_end = self.request.GET.get('cheap_end')
        if cheap_end:
            soft = soft.filter(price__lte=cheap_end)

        return soft

    def list(self, request: Request, *args, **kwargs):
        result = add_count_option(self, request)
        if result:
            return result

        draft = get_draft(request)
        data = self.serializer_class(self.get_queryset(), many=True,
                                     context={'request': request}).data
        return Response({
            'draft_id': draft.id if draft else None,
            'soft_list': data
        })

    def destroy(self, request: Request,  *args, **kwargs):
        soft = get_model_obj(Soft, kwargs.get('pk'))
        if soft.status == SOFT_STATUSES[-1]:
            raise NotFound({'detail': 'this soft already deleted'})

        soft.status = SOFT_STATUSES[-1]
        soft.save()
        return Response(status=204)


def validate_date(date: str, field: str):
    try:
        return datetime.strptime(date, "%Y-%m-%d")
    except ValueError:
        raise ValidationError({'detail': field + ' field date format is incorrect.'})


# Getting and logically deleting payments:
class PaymentViewSet(ModelViewSet):
    serializer_class = PaymentSerializer
    queryset = Payment.objects.none()

    http_method_names = ['get', 'delete']

    def get_permissions(self):
        permission_classes = []
        match self.action:
            # Viewing of all list is protected from user:
            case 'list' | 'retrieve':
                permission_classes = [IsUser | IsManager | IsAdmin]
            case 'destroy':
                permission_classes = [IsUser]
        return [permission() for permission in permission_classes]

    def get_queryset(self):
        payments = Payment.objects.all().exclude(status__in=[PAYMENT_STATUSES[0], PAYMENT_STATUSES[-1]])

        # Viewing of all list protection from user:
        user = self.request.user
        if not user.is_superuser and not user.is_staff:
            payments = payments.filter(user=user.id)

        # Filters:
        code = self.request.GET.get('code')
        if code:
            payments = payments.filter(code=code)

        start = self.request.GET.get('start_date')
        if start:
            payments = payments.filter(date_open__gte=validate_date(start, 'start_date'))

        end = self.request.GET.get('end_date')
        if end:
            payments = payments.filter(date_open__lte=validate_date(end, 'end_date'))

        status = self.request.GET.get('status')
        if status:
            if status not in PAYMENT_STATUSES:
                raise ValidationError({'detail': 'wrong status specified'})
            payments = payments.filter(status=status)

        return payments

    def list(self, request: Request, *args, **kwargs):
        result = add_count_option(self, request)
        if result:
            return result

        # Ability to check summ of all payments matching query:
        if request.GET.get('sum') == 'true':
            return Response({
                'today_requested':
                    self.get_queryset().aggregate(summ_req=Sum('soft__price'))['summ_req']
            })

        return super().list(request, args, kwargs)

    def retrieve(self, request, *args, **kwargs):
        payment = get_model_obj(Payment, kwargs.get('pk'))  # Because get_queryset takes opened away
        if payment.status == PAYMENT_STATUSES[-1]:
            raise NotFound({'detail': 'payment not found'})

        if payment.user != request.user:
            raise PermissionDenied()

        return Response(self.get_serializer(payment).data)

    def destroy(self, request: Request, *args, **kwargs):
        payment = get_model_obj(Payment, kwargs.get('pk'))  # Same

        # Not to allow to user to delete other users payments:
        if payment.user != request.user:
            raise PermissionDenied()

        if payment.status == PAYMENT_STATUSES[-1]:
            raise NotFound({'detail': 'this payment already deleted'})

        payment.status = PAYMENT_STATUSES[-1]
        payment.save()
        return Response(status=204)


# Manging status of payment for admin:
class PaymentStatusAdminView(APIView):
    permission_classes = [IsManager | IsAdmin]

    def put(self, request, *args, **kwargs):
        payment = get_model_obj(Payment, kwargs.get('pk'))

        if payment.status == PAYMENT_STATUSES[-1]:
            raise NotFound({'detail': 'there is no such payment'})

        if payment.status != PAYMENT_STATUSES[1]:
            raise PermissionDenied({'detail': 'you cant change status now'})

        status = request.data.get('status')
        if status not in [PAYMENT_STATUSES[-3], PAYMENT_STATUSES[-2]]:
            raise PermissionDenied({'detail': 'wrong status specified'})

        payment.manager = request.user
        payment.status = status
        payment.save()

        return Response(PaymentSerializer(payment).data)


# Manging status of payment for user:
class PaymentStatusUserView(APIView):
    permission_classes = [IsUser]

    def put(self, request, *args, **kwargs):
        payment = get_draft(request)
        if not payment:
            raise NotFound({'detail': 'draft not found'})

        payment.status = PAYMENT_STATUSES[1]
        payment.save()
        return Response(PaymentSerializer(payment).data)


# Soft inside draft managing:
class PaymentSoftView(APIView):
    permission_classes = [IsUser]

    def put(self, request, *args, **kwargs):
        payment = get_draft(request)
        soft = get_model_obj(Soft, request.data.get('soft'))

        # Creating draft if needed:
        if not payment:
            payment = Payment.objects.create(user=request.user,
                                             status=PAYMENT_STATUSES[0])

        # Adding soft if not already added:
        if not payment.soft.filter(id=soft.id).exists():
            payment.soft.add(soft)

        return Response(PaymentSerializer(payment, context={'request': request}).data)

    def delete(self, request, *args, **kwargs):
        payment = get_draft(request)
        if not payment:
            raise NotFound({'detail': 'draft not found'})

        soft = get_model_obj(Soft, request.data.get('soft'), force_empty=True)
        payment.soft.remove(soft)

        return Response(PaymentSerializer(payment, context={'request': request}).data)


class FileViewSet(ModelViewSet):
    serializer_class = FilesSerialiser
    queryset = File.objects.all()

    http_method_names = ['get', 'post', 'delete']

    def get_permissions(self):
        match self.action:
            case 'retrieve':
                permission_classes = [IsUser | IsManager | IsAdmin]
            case _:
                permission_classes = [IsManager | IsAdmin]
        return [permission() for permission in permission_classes]

    def retrieve(self, request, *args, **kwargs):
        try:
            file = File.objects.get(id=self.kwargs.get('pk'))

            # Users can download only files of soft payment of which is finished:
            user = self.request.user

SoftLoading/views.py
from django.http import HttpRequest
from django.shortcuts import render
from SoftLoading.models import *
from django.db.models import Q
import psycopg2
from Site.settings import CONFIG
from SoftLoading.validators import SOFT_STATUSES


con = psycopg2.connect(
    database=CONFIG.get('Postgres DB', 'name'),
    user=CONFIG.get('Postgres DB', 'user'),
    password=CONFIG.get('Postgres DB', 'password'),
    host=CONFIG.get('Postgres DB', 'host'),
    port=CONFIG.get('Postgres DB', 'port')
)
con.set_isolation_level(0)


cur = con.cursor()
cur.execute('SELECT * FROM "Payments"')
results = cur.fetchall()
print('Payments:')
[print(paiment) for paiment in results]
print()

cur.execute('SELECT * FROM "Soft"')
results = cur.fetchall()
print('Soft:')
[print(soft) for soft in results]


def short_field(value):
    return value[:34] + ('...' if len(value) > 34 else '')


def get_soft_data(soft, extended=False, files=None):
    data = {
        'id': soft.id,
        'name': soft.name if extended else short_field(soft.name) ,
        'image': soft.image.url if soft.image else None,
        'price': soft.price,
        'description': soft.description  if extended else short_field(soft.description)
    }
    if extended:
        data.update({'files': files})

    return data


def catalog(request: HttpRequest):
    # Processing deleting:
    soft_id = request.POST.get('delete')
    if soft_id:
        with con.cursor() as curs:
            curs.execute(f"UPDATE \"Soft\" SET status='{SOFT_STATUSES[-1]}' WHERE id = {soft_id}")
        print('Deletion done,', soft_id)

    softs = Soft.objects.filter(status=SOFT_STATUSES[0])

    # Processing search and filter:
    search = request.POST.get('search')
    if search:
        softs = softs.filter(
            Q(name__icontains=search) | Q(description__icontains=search) |
            (Q(price=search) if search.isnumeric() else Q(pk__in=[])) |
            Q(file__platform__icontains=search)
        ).distinct()

    filter = request.POST.get('filter')
    match filter:
        case 'up':
            softs = softs.order_by('price')
        case 'down':
            softs = softs.order_by('-price')

    # Amount condition:
    try:
        softs = softs[:int(request.POST.get('amount'))]
    except:
        pass

    soft_list = [get_soft_data(soft) for soft in softs]

    return render(request, 'SoftLoading/catalog.html', {'soft_list': soft_list,
                                                        'search_text': search if search else '',
                                                        'filter': filter})


def soft(request, soft_id):
    soft = get_soft_data(
        Soft.objects.get(id=soft_id), extended=True, files=File.objects.filter(soft_id=soft_id),
    )
    return render(request, 'SoftLoading/soft.html', {'soft': soft})

SoftLoading/templates/SoftLoading/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

   <link  rel="icon" href = "{% static 'SoftLoading/src/icon.svg' %}">
    <title>Soft Loading</title>

    <!-- Bootstrap JS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
          crossorigin="anonymous">
    <link rel="stylesheet" href ="{% static 'SoftLoading/css/style.css'  %}">


</head>


<body>
    <div class=" wrapper main_wrapper">
        {% include 'SoftLoading/header.html' %}
        {% block content %}{% endblock %}
    </div>
</body>


<!-- Bootstrap JS and dependencies -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</html>

SoftLoading/templates/SoftLoading/card.html
{% load static %}
{% block content %}


<a href="{% url 'soft_loading:soft' soft.id %}">
    <div class="card">
        <div className="text-center">
            <img class="skrug w-100" src="{{ soft.image }}"
                 onerror="this.src='{% static 'SoftLoading/src/placeholder.jpg' %}'">
        </div>
        <div class="d-flex justify-between align-center">
            <div class="d-flex flex-column">
                <span>Название:</span>
                <b>{{ soft.name }}</b>
                <span>Описание:</span>
                <b>{{ soft.description }}</b>
                <span>Цена:</span>
                <b>{{ soft.price }}</b>
            </div>
        </div>
         <form method="post" class="d-flex justify-content-center w-100 ">
             {% csrf_token %}
             <input name="delete" style="display: none;" value="{{ soft.id }}">
             <button type="submit" class="btn  btn-primary danger">delete</button>
         </form>
    </div>
</a>
{% endblock %}

SoftLoading/templates/SoftLoading/catalog.html
{% extends 'SoftLoading/base.html' %}
{% load static %}

{% block content %}
<div class="BC">
    <p class="br_c"><a class="BC_link" href="/">Главная</a>
        / <a class="BC_link" href="{% url 'SoftLoading:catalog'%}">Каталог</a></p>
</div>
<div class="content p-40">
    <div class="header d-flex align-center justify-between">
        <h2 className="mb-0 w-100">Все программы</h2>
        <div class="d-flex align-items-center justify-content-end content w-100">
            <form id="searchForm" method="post" class="d-none d-sm-flex inputField">
                {% csrf_token %}
                <div class="input-group">
                    <label for="search" class="sr-only"><span>Поиск:</span></label>
                    <input id="search" class="form-control border-dark mr-2" name="search" type="text"
                           value="{{search_text}}"
                           style="border-width: 2px; border-radius: 5px;">
                    <button class="btn btn-primary" type="submit">Поиск</button>
                </div>
            </form>
        </div>
    </div>
</div>


<div class="d-flex">
    {% if not soft_list %}
    <h1>Каталог пуст..</h1>
    {% else %}
    <div class="row g-4">
        {% for soft in soft_list %}
        <div class="col-md-4 col-lg-3" id="{{ forloop.counter }}">
            {% include 'SoftLoading/card.html' with soft=soft %}
        </div>
        {% endfor %}
    </div>
    {% endif %}
</div>
</div>
{% endblock %}

SoftLoading/templates/SoftLoading/header.html
{% load static %}

<div class="d-flex align-center">
    <img width="100" height="100" src="{% static 'SoftLoading/src/logo.png' %}" alt="Логотип"/>
    <div class="d-flex flex-column">
        <h3 class="text-uppercase site_header">Магазин софта</h3>
        <p>Есть чем удивить</p>
    </div>
</div>

SoftLoading/templates/SoftLoading/soft.html
{% extends 'SoftLoading/base.html' %}
{% load static %}


{% block content %}
<div class="BC">
    <p class="br_c"><a class="BC_link" href="/">Главная</a>
        / <a class="BC_link">{{soft.name}}</a></p>
</div>
<ul class="content p-15 flex-row">
    <h2 class="mb-0 d-flex flex-column flex-sm-row justify-between sm text-center">
        {{ soft.name }}
    </h2>
    <div class="text-center">
        <img class="wrapper align-center mt-15 mb-10 w-75" src="{{ soft.image }}"
             style="margin-bottom: 15px; margin-top: 25px;"
             onerror="this.src='{% static 'SoftLoading/src/placeholder.jpg' %}'"/>
        <h3 style=" margin-top: 0px; ">Цена: {{soft.price}} ₽</h3>
    </div>
    <h3>Описание:</h3>
    <li class="mb-25 ml-25" style="margin-left: 25px; margin-top: 25 px; margin-bottom: 25px;">{{ soft.description }}
    </li>
    <h3 class="mb-0">Файлы:</h3>
    <div class="w-100 text-center">
        <div class="w-100 text-center">
            <div class="mt-15 d-inline-block">
                {% if not soft.files or not soft.files|length %}
                <h2>...</h2>
                {% else %}
                {% for file in soft.files %}
                <div class="file-card">
                    <div class="file-details d-flex align-center mr-5">
                        <b>{{ file.size }}</b>
                        <b>{{ file.platform }}</b>
                        <b>{{ file.architecture }}</b>
                    </div>
                    <div class="buttons flex-column flex-sm-row ml-10">
                        <a class="btn btn-primary download-button" href="/media/{{file.file}}" download>
                            Скачать
                        </a>
                    </div>
                </div>
                {% endfor %}
                {% endif %}
            </div>
        </div>

    </div>
</ul>
</div>
{% endblock %}